TEMPLATE = app
DESTDIR = dist
TARGET = yaca
VERSION = 1.0.0
CONFIG -= debug_and_release app_bundle lib_bundle
CONFIG += debug 
QT = core gui
SOURCES += algo/Vigenere.cpp main.cpp algo/Scytale.cpp ui/VigenereUI.cpp algo/Caesar.cpp algo/BaseAlgo.cpp ui/UI.cpp ui/CaesarUI.cpp ui/ScytaleUI.cpp
HEADERS += algo/Scytale.h ui/ScytaleUI.h ui/VigenereUI.h algo/BaseAlgo.h ui/CaesarUI.h ui/UI.h algo/Caesar.h algo/Vigenere.h
OBJECTS_DIR = build
QMAKE_CC = gcc
QMAKE_CXX = g++
